import type { Metadata } from "next";
import Link from "next/link";

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || "https://soraipixel.com";

export const metadata: Metadata = {
  title: "AI Jewelry Photography — Transform Product Photos with AI",
  description:
    "AI jewelry photography that turns phone snaps into studio-quality product images in seconds. Hero shots, close-ups, model photos, lifestyle scenes. No photographer, no studio, no waiting. Try free.",
  keywords: [
    "AI jewelry photography",
    "AI photography",
    "AI product photography",
    "jewelry photography AI",
    "AI photo editor jewelry",
    "automated jewelry photography",
    "AI generated jewelry photos",
    "jewelry image AI",
    "product photography AI",
    "AI photography tool",
    "jewelry ecommerce photos AI",
  ],
  alternates: { canonical: "/ai-jewelry-photography" },
  openGraph: {
    title: "AI Jewelry Photography — Studio-Quality Images from Any Photo",
    description:
      "Upload a phone snap, get magazine-quality jewelry images back. AI photography that keeps every detail perfect.",
    url: `${SITE_URL}/ai-jewelry-photography`,
    siteName: "SoraiPixel",
    type: "website",
    images: [
      {
        url: `${SITE_URL}/images/hero-jewelry.png`,
        width: 1376,
        height: 768,
        alt: "AI Jewelry Photography by SoraiPixel",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "AI Jewelry Photography — Studio-Quality in Seconds",
    description:
      "No photographer. No studio. Just AI. Transform any jewelry photo into professional product images.",
    images: [`${SITE_URL}/images/hero-jewelry.png`],
  },
};

const problems = [
  {
    icon: (
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
        <circle cx="12" cy="12" r="10" />
        <path d="M16 16s-1.5-2-4-2-4 2-4 2" />
        <line x1="9" y1="9" x2="9.01" y2="9" /><line x1="15" y1="9" x2="15.01" y2="9" />
      </svg>
    ),
    title: "Studio Shoots Cost ₹5,000–₹50,000 Per Session",
    desc: "Professional jewelry photography requires expensive equipment, lighting rigs, and skilled photographers. Most small brands simply can't afford it.",
  },
  {
    icon: (
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
        <circle cx="12" cy="12" r="10" /><polyline points="12 6 12 12 16 14" />
      </svg>
    ),
    title: "Days of Waiting for a Single Collection",
    desc: "Booking a photographer, shipping products, and waiting for retouched images takes 1–3 weeks. New collections sit unlisted while you wait.",
  },
  {
    icon: (
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
        <path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z" />
        <line x1="12" y1="9" x2="12" y2="13" /><line x1="12" y1="17" x2="12.01" y2="17" />
      </svg>
    ),
    title: "Phone Photos Don't Sell",
    desc: "Listings with amateur photos get 60% fewer clicks. Without professional imagery, your beautiful jewelry looks ordinary.",
  },
];

const howItWorks = [
  {
    step: "01",
    title: "Upload Any Photo",
    desc: "Phone snap, CAD render, or existing product shot. Our AI jewelry photography system handles any input quality.",
  },
  {
    step: "02",
    title: "AI Generates Studio Shots",
    desc: "In under 10 seconds, AI creates hero shots, close-ups, model photos, and lifestyle scenes — while preserving every design detail.",
  },
  {
    step: "03",
    title: "Download & List",
    desc: "Get marketplace-ready images instantly. Push directly to Shopify, or download high-res files for any platform.",
  },
];

const photoTypes = [
  {
    title: "Hero Shots",
    desc: "The signature front-facing product image that anchors every listing. Perfect lighting, controlled shadows, zero reflections.",
    keywords: "AI product photography, hero shot",
  },
  {
    title: "Close-Up Detail",
    desc: "AI-enhanced macro photography that reveals every stone facet, prong setting, and metal texture your customers need to see.",
    keywords: "AI macro photography, jewelry detail",
  },
  {
    title: "On-Model Photography",
    desc: "AI-generated models wearing your jewelry. Choose skin tone, pose, and style. No model fees, no scheduling, no photoshoot.",
    keywords: "AI model photography, virtual try-on",
  },
  {
    title: "Lifestyle Scenes",
    desc: "Place your jewelry in real-world contexts — marble surfaces, velvet displays, golden hour scenes — all generated by AI.",
    keywords: "AI lifestyle photography, product styling",
  },
  {
    title: "Angle Packs",
    desc: "Multiple angles from a single photo. Front, side, 45-degree, and flat-lay — consistent style across every shot.",
    keywords: "multi-angle product photography",
  },
  {
    title: "Metal Recoloring",
    desc: "Show the same design in gold, silver, rose gold, and platinum without re-shooting. AI handles the material change photorealistically.",
    keywords: "AI photo editing, metal recolor",
  },
];

const stats = [
  { value: "96.2%", label: "Detail Preservation" },
  { value: "<10s", label: "Generation Time" },
  { value: "90%", label: "Cost Reduction vs Studio" },
  { value: "3x", label: "Higher Conversion Rate" },
];

const faqs = [
  {
    q: "What is AI jewelry photography?",
    a: "AI jewelry photography uses artificial intelligence to transform ordinary product photos into studio-quality images. Instead of hiring a photographer, renting a studio, and waiting days for retouched images, you upload a single photo and AI generates professional hero shots, close-ups, model photos, and lifestyle scenes in seconds.",
  },
  {
    q: "How is AI photography different from photo editing?",
    a: "Traditional photo editing (Photoshop, Lightroom) enhances existing photos. AI photography goes further — it generates entirely new scenes, adds realistic models, creates new lighting setups, and produces images that would require a full studio shoot. The AI preserves your exact jewelry design while creating professional-grade compositions.",
  },
  {
    q: "Will AI change the look of my jewelry?",
    a: "No. SoraiPixel's AI is specifically trained to preserve every detail of your jewelry — every stone, prong, engraving, and metal texture. The AI changes the scene, lighting, and context, but your product remains pixel-perfect.",
  },
  {
    q: "What quality photo do I need to upload?",
    a: "Any photo works — phone camera, CAD render, or existing product shot. The AI handles low-light corrections, background removal, and quality enhancement automatically. Better input photos do produce better results, but even a basic phone snap works well.",
  },
  {
    q: "Can I use AI-generated photos on my ecommerce store?",
    a: "Yes. All images generated are yours to use commercially — on Shopify, Amazon, Etsy, Instagram, or any marketplace. SoraiPixel even has direct Shopify integration to push listings with one click.",
  },
  {
    q: "How much does AI jewelry photography cost compared to a studio?",
    a: "A professional jewelry photography session costs ₹5,000–₹50,000. With SoraiPixel, you start free with 8 daily tokens. Paid plans start at a fraction of a single studio session, and you can generate unlimited varieties.",
  },
];

export default function AIJewelryPhotographyPage() {
  const faqJsonLd = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map((f) => ({
      "@type": "Question",
      name: f.q,
      acceptedAnswer: { "@type": "Answer", text: f.a },
    })),
  };

  const breadcrumbJsonLd = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home", item: SITE_URL },
      {
        "@type": "ListItem",
        position: 2,
        name: "AI Jewelry Photography",
        item: `${SITE_URL}/ai-jewelry-photography`,
      },
    ],
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }}
      />

      <div className="min-h-screen bg-background text-foreground">
        {/* Hero */}
        <section className="relative overflow-hidden pt-24 pb-16 sm:pt-32 sm:pb-24">
          <div className="absolute inset-0 bg-gradient-to-b from-[rgba(196,166,125,0.06)] to-transparent" />
          <div className="relative max-w-5xl mx-auto px-4 sm:px-6 text-center">
            <p className="text-xs sm:text-sm font-medium tracking-widest uppercase text-[#c4a67d] mb-4">
              AI-Powered Product Photography
            </p>
            <h1 className="text-3xl sm:text-5xl lg:text-6xl font-bold leading-tight tracking-tight mb-6">
              <span className="text-[#c4a67d]">AI Jewelry Photography</span>
              <br />
              <span className="text-foreground">Studio-Quality Images from Any Photo</span>
            </h1>
            <p className="max-w-2xl mx-auto text-base sm:text-lg text-text-secondary leading-relaxed mb-8">
              Upload a phone snap or CAD render. In seconds, AI generates hero shots, close-ups,
              model photos, and lifestyle scenes — preserving every detail of your jewelry design.
              No photographer. No studio. No waiting.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-3">
              <Link
                href="/jewelry"
                className="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-[#c4a67d] text-[#1a1a2e] font-semibold text-sm hover:bg-[#d4b88d] transition-all shadow-lg shadow-[rgba(196,166,125,0.25)]"
              >
                Try AI Photography Free
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M5 12h14" /><path d="m12 5 7 7-7 7" /></svg>
              </Link>
              <Link
                href="/gallery"
                className="inline-flex items-center gap-2 px-6 py-3 rounded-xl border border-border text-text-secondary font-medium text-sm hover:border-[#c4a67d] hover:text-[#c4a67d] transition-all"
              >
                See Examples
              </Link>
            </div>

            {/* Stats bar */}
            <div className="mt-12 grid grid-cols-2 sm:grid-cols-4 gap-4 max-w-3xl mx-auto">
              {stats.map((s) => (
                <div key={s.label} className="text-center">
                  <div className="text-2xl sm:text-3xl font-bold text-[#c4a67d]">{s.value}</div>
                  <div className="text-xs text-text-secondary mt-1">{s.label}</div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Problem Section */}
        <section className="py-16 sm:py-24 border-t border-border">
          <div className="max-w-5xl mx-auto px-4 sm:px-6">
            <div className="text-center mb-12">
              <h2 className="text-2xl sm:text-3xl font-bold mb-3">
                Why Jewelry Brands Struggle with Product Photography
              </h2>
              <p className="text-text-secondary max-w-2xl mx-auto">
                Professional jewelry photography is expensive, slow, and inaccessible for most sellers.
                AI photography changes that completely.
              </p>
            </div>
            <div className="grid sm:grid-cols-3 gap-6">
              {problems.map((p) => (
                <div
                  key={p.title}
                  className="rounded-2xl border border-border bg-surface p-6 hover:border-[rgba(196,166,125,0.3)] transition-colors"
                >
                  <div className="w-10 h-10 rounded-lg bg-[rgba(196,166,125,0.1)] flex items-center justify-center text-[#c4a67d] mb-4">
                    {p.icon}
                  </div>
                  <h3 className="font-semibold text-foreground mb-2">{p.title}</h3>
                  <p className="text-sm text-text-secondary leading-relaxed">{p.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* How It Works */}
        <section className="py-16 sm:py-24 bg-surface border-t border-border">
          <div className="max-w-5xl mx-auto px-4 sm:px-6">
            <div className="text-center mb-12">
              <h2 className="text-2xl sm:text-3xl font-bold mb-3">
                How AI Jewelry Photography Works
              </h2>
              <p className="text-text-secondary max-w-2xl mx-auto">
                Three steps. Under 30 seconds. From raw photo to marketplace-ready imagery.
              </p>
            </div>
            <div className="grid sm:grid-cols-3 gap-8">
              {howItWorks.map((s) => (
                <div key={s.step} className="text-center">
                  <div className="w-12 h-12 rounded-full border-2 border-[#c4a67d] flex items-center justify-center text-[#c4a67d] font-bold text-lg mx-auto mb-4">
                    {s.step}
                  </div>
                  <h3 className="font-semibold text-foreground text-lg mb-2">{s.title}</h3>
                  <p className="text-sm text-text-secondary leading-relaxed">{s.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Photo Types */}
        <section className="py-16 sm:py-24 border-t border-border">
          <div className="max-w-5xl mx-auto px-4 sm:px-6">
            <div className="text-center mb-12">
              <h2 className="text-2xl sm:text-3xl font-bold mb-3">
                What AI Photography Can Generate
              </h2>
              <p className="text-text-secondary max-w-2xl mx-auto">
                Every image type you need for professional jewelry listings — all from a single upload.
              </p>
            </div>
            <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
              {photoTypes.map((t) => (
                <div
                  key={t.title}
                  className="rounded-2xl border border-border bg-surface p-6 hover:border-[rgba(196,166,125,0.3)] transition-colors group"
                >
                  <h3 className="font-semibold text-foreground mb-2 group-hover:text-[#c4a67d] transition-colors">
                    {t.title}
                  </h3>
                  <p className="text-sm text-text-secondary leading-relaxed">{t.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Who It's For */}
        <section className="py-16 sm:py-24 bg-surface border-t border-border">
          <div className="max-w-5xl mx-auto px-4 sm:px-6">
            <div className="text-center mb-12">
              <h2 className="text-2xl sm:text-3xl font-bold mb-3">
                Who Uses AI Jewelry Photography
              </h2>
            </div>
            <div className="grid sm:grid-cols-3 gap-6">
              {[
                {
                  title: "Jewelry Brands & Retailers",
                  desc: "Replace expensive studio sessions. Generate consistent, professional product images across entire collections in minutes instead of weeks.",
                },
                {
                  title: "Etsy, Amazon & Online Sellers",
                  desc: "Professional photos sell 3x more. AI photography gives every seller access to studio-quality imagery, regardless of budget.",
                },
                {
                  title: "Manufacturers & Wholesalers",
                  desc: "Bulk-generate listings for hundreds of SKUs with consistent style. Metal recoloring and model shots included.",
                },
              ].map((u) => (
                <div
                  key={u.title}
                  className="rounded-2xl border border-border p-6 hover:border-[rgba(196,166,125,0.3)] transition-colors"
                >
                  <h3 className="font-semibold text-foreground mb-2">{u.title}</h3>
                  <p className="text-sm text-text-secondary leading-relaxed">{u.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* FAQ */}
        <section className="py-16 sm:py-24 border-t border-border">
          <div className="max-w-3xl mx-auto px-4 sm:px-6">
            <div className="text-center mb-12">
              <h2 className="text-2xl sm:text-3xl font-bold mb-3">
                Frequently Asked Questions about AI Photography
              </h2>
            </div>
            <div className="space-y-4">
              {faqs.map((f) => (
                <details
                  key={f.q}
                  className="group rounded-xl border border-border bg-surface overflow-hidden"
                >
                  <summary className="flex items-center justify-between cursor-pointer px-5 py-4 text-sm font-medium text-foreground hover:text-[#c4a67d] transition-colors">
                    {f.q}
                    <svg
                      width="16"
                      height="16"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                      className="flex-shrink-0 ml-3 transition-transform group-open:rotate-180"
                    >
                      <polyline points="6 9 12 15 18 9" />
                    </svg>
                  </summary>
                  <div className="px-5 pb-4 text-sm text-text-secondary leading-relaxed">
                    {f.a}
                  </div>
                </details>
              ))}
            </div>
          </div>
        </section>

        {/* CTA */}
        <section className="py-16 sm:py-24 border-t border-border">
          <div className="max-w-3xl mx-auto px-4 sm:px-6 text-center">
            <h2 className="text-2xl sm:text-3xl font-bold mb-4">
              Ready to Try AI Jewelry Photography?
            </h2>
            <p className="text-text-secondary mb-8 max-w-xl mx-auto">
              Start free with 8 daily tokens — 1 free image every day. No credit card required.
              Upload your first jewelry photo and see the results in seconds.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-3">
              <Link
                href="/jewelry"
                className="inline-flex items-center gap-2 px-8 py-3.5 rounded-xl bg-[#c4a67d] text-[#1a1a2e] font-semibold text-sm hover:bg-[#d4b88d] transition-all shadow-lg shadow-[rgba(196,166,125,0.25)]"
              >
                Start Free — No Card Needed
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M5 12h14" /><path d="m12 5 7 7-7 7" /></svg>
              </Link>
              <Link
                href="/pricing"
                className="inline-flex items-center gap-2 px-6 py-3.5 rounded-xl border border-border text-text-secondary font-medium text-sm hover:border-[#c4a67d] hover:text-[#c4a67d] transition-all"
              >
                View Pricing Plans
              </Link>
            </div>
          </div>
        </section>
      </div>
    </>
  );
}
